version: '3.0.{build}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
image: Visual Studio 2019
before_build:
  - ps: dotnet restore ./src
build_script:
#  - ps: dotnet build ./src --version-suffix "beta" --no-restore --configuration Release
  - ps: dotnet build ./src --no-restore --configuration Release
test_script:
  - ps: dotnet test ./src --no-restore --no-build --configuration Release
after_build:
#  - ps: dotnet pack ./src --version-suffix "beta" --no-restore --no-build --configuration Release -o ./pack
  - ps: dotnet pack ./src --no-restore --no-build --configuration Release -o ./pack
artifacts:
  - path: '**\*.nupkg'